export const szenarien = [
    "Was wäre, wenn du Gedanken lesen könntest?",
    "Was wäre, wenn du unsichtbar wärst?",
    "Was wäre, wenn du die Zeit zurückdrehen könntest?",
    "Was wäre, wenn du mit Tieren sprechen könntest?",
    "Was wäre, wenn du nie wieder schlafen müsstest?",
    "Was wäre, wenn du unsterblich wärst?",
    "Was wäre, wenn du jeden Wunsch frei hättest?",
    "Was wäre, wenn du in einer anderen Zeit leben würdest?",
    "Was wäre, wenn du ein berühmter Musiker wärst?",
    "Was wäre, wenn du ein gefeierter Künstler wärst?",
    "Was wäre, wenn du ein erfolgreicher Unternehmer wärst?",
    "Was wäre, wenn du ein Weltraumforscher wärst?",
    "Was wäre, wenn du ein Abenteuer in einem Dschungel erleben würdest?",
    "Was wäre, wenn du einen Schatz finden würdest?",
    "Was wäre, wenn du auf einer einsamen Insel stranden würdest?",
    "Was wäre, wenn du ein Leben unter Wasser führen könntest?",
    "Was wäre, wenn du in einem Märchen leben würdest?",
    "Was wäre, wenn du ein Superheld wärst?",
    "Was wäre, wenn du ein Bösewicht wärst?",
    "Was wäre, wenn du die Welt retten müsstest?",
    "Was wäre, wenn du deinen Doppelgänger treffen würdest?",
    "Was wäre, wenn du dein jüngeres Ich treffen könntest?",
    "Was wäre, wenn du wüsstest, wann du sterben wirst?",
    "Was wäre, wenn du dein Leben neu starten könntest?",
    "Was wäre, wenn du deine größte Angst überwinden müsstest?",
    "Was wäre, wenn du eine wichtige Entscheidung für die Menschheit treffen müsstest?",
    "Was wäre, wenn du die Wahrheit über das Universum erfahren würdest?",
    "Was wäre, wenn du eine außerirdische Zivilisation treffen würdest?",
    "Was wäre, wenn du auf einem anderen Planeten leben könntest?",
    "Was wäre, wenn du die Technologie der Zukunft hättest?",
    "Was wäre, wenn es keine Gesetze gäbe?",
    "Was wäre, wenn Geld keine Rolle mehr spielen würde?",
    "Was wäre, wenn jeder ehrlich zueinander wäre?",
    "Was wäre, wenn es keine Kriege mehr gäbe?",
    "Was wäre, wenn die Umwelt sich von selbst heilen würde?",
    "Was wäre, wenn du deine verlorene Liebe wiederfinden würdest?",
    "Was wäre, wenn du einen Fehler aus deiner Vergangenheit ungeschehen machen könntest?",
    "Was wäre, wenn du deine größte Inspiration treffen könntest?",
    "Was wäre, wenn du ein Tier für einen Tag wärst?",
    "Was wäre, wenn du ein berühmtes Kunstwerk besitzen würdest?",
    "Was wäre, wenn du ein historisches Ereignis miterleben könntest?",
    "Was wäre, wenn du ein Buch schreiben würdest, das die Welt verändert?",
    "Was wäre, wenn du einen Film drehen würdest, der in die Geschichte eingeht?",
    "Was wäre, wenn du ein bahnbrechendes wissenschaftliches Experiment durchführen würdest?",
    "Was wäre, wenn du eine neue Sprache in einer Stunde lernen könntest?",
    "Was wäre, wenn du jedes Instrument perfekt spielen könntest?",
    "Was wäre, wenn du dich an jedes Detail deines Lebens erinnern könntest?",
    "Was wäre, wenn du deine Träume steuern könntest?",
    "Was wäre, wenn du die Zukunft vorhersagen könntest?",
    "Was wäre, wenn du plötzlich in einem Videospiel aufwachst?",
    "Was wäre, wenn du die Fähigkeit hättest, Gegenstände mit deinen Gedanken zu bewegen?",
    "Was wäre, wenn du für einen Tag das Geschlecht wechseln würdest?",
    "Was wäre, wenn du herausfinden würdest, dass du adoptiert wurdest?",
    "Was wäre, wenn du die perfekte Mahlzeit für den Rest deines Lebens essen müsstest?",
    "Was wäre, wenn du die Antwort auf eine der großen ungelösten Fragen der Menschheit wüsstest?",
    "Was wäre, wenn du einen Tag lang die Kontrolle über die Welt hättest?",
    "Was wäre, wenn du die Fähigkeit hättest, dich in jedes Tier zu verwandeln?",
    "Was wäre, wenn du die wahre Bedeutung des Lebens entdecken würdest?",
    "Was wäre, wenn du deinen größten Helden treffen könntest?",
    "Was wäre, wenn du die Fähigkeit hättest, durch Wände zu gehen?",
    "Was wäre, wenn du die perfekte Partnerschaft finden würdest?",
    "Was wäre, wenn du die Fähigkeit hättest, jede Krankheit zu heilen?",
    "Was wäre, wenn du ein verstecktes Talent entdecken würdest?",
    "Was wäre, wenn du die Fähigkeit hättest, die Gefühle anderer zu spüren?",
    "Was wäre, wenn du einen Brief von deinem zukünftigen Ich erhalten würdest?",
    "Was wäre, wenn du die Fähigkeit hättest, die Sprache des Universums zu verstehen?",
    "Was wäre, wenn du einen Tag lang berühmt wärst?",
    "Was wäre, wenn du die Fähigkeit hättest, die Vergangenheit zu verändern?",
    "Was wäre, wenn du deinen größten Fehler ungeschehen machen könntest?",
    "Was wäre, wenn du die Fähigkeit hättest, dich überallhin zu teleportieren?",
    "Was wäre, wenn du deinen Seelenverwandten treffen würdest?",
    "Was wäre, wenn du die Fähigkeit hättest, die Zukunft zu sehen?",
    "Was wäre, wenn du deinen größten Traum verwirklichen könntest?",
    "Was wäre, wenn du die Fähigkeit hättest, die Realität zu verändern?",
    "Was wäre, wenn du herausfinden würdest, dass du eine königliche Abstammung hast?",
    "Was wäre, wenn du die Fähigkeit hättest, die Zeit anzuhalten?",
    "Was wäre, wenn du deinen idealen Job finden würdest?",
    "Was wäre, wenn du die Fähigkeit hättest, dich selbst zu klonen?",
    "Was wäre, wenn du eine magische Fähigkeit deiner Wahl hättest?",
    "Was wäre, wenn du die Fähigkeit hättest, in die Gedanken anderer einzutauchen?",
    "Was wäre, wenn du deinen größten Verlust ersetzen könntest?",
    "Was wäre, wenn du die Fähigkeit hättest, die Elemente zu kontrollieren?",
    "Was wäre, wenn du deinen größten Wunsch in Erfüllung gehen sehen würdest?",
    "Was wäre, wenn du die Fähigkeit hättest, die Gesetze der Physik zu beugen?",
    "Was wäre, wenn du herausfinden würdest, dass du eine besondere Bestimmung hast?",
    "Was wäre, wenn du die Fähigkeit hättest, dich in jedes Lebewesen zu verwandeln?",
    "Was wäre, wenn du deinen größten Erfolg noch einmal erleben könntest?"
];